import AppKit
import CryptoKit
import OSLog
import Vision

nonisolated struct ClipboardItem: Sendable {
    let id: Int
    let contentType: ContentType
    let textContent: String
    let sourceApp: String
    let sourceBundleId: String
    let imagePath: String
    let imageWidth: Int
    let imageHeight: Int
    let imageSize: Int
    var ocrText: String
    let timestamp: TimeInterval

    enum ContentType: String, Sendable {
        case text
        case image
    }
}

actor ClipboardStore {

    deinit {
        setupTask?.cancel()
        timer?.cancel()
        for task in ocrTasks.values { task.cancel() }
    }

    // MARK: - Constants

    private let maxTextLength = 10240
    private let pollInterval: TimeInterval = 0.5
    private let minOCRDimension = 100

    private static let concealedTypeRaw = "org.nspasteboard.ConcealedType"
    private static let transientTypeRaw = "org.nspasteboard.TransientType"
    private static let concealedType = NSPasteboard.PasteboardType(concealedTypeRaw)
    private static let transientType = NSPasteboard.PasteboardType(transientTypeRaw)

    private static let concealedTypes: Set<String> = [
        concealedTypeRaw,
        transientTypeRaw,
        "org.nspasteboard.AutoGeneratedType",
        "com.agilebits.onepassword",
        "de.petermaurer.TransientPasteboardType",
        "com.typeit4me.clipping",
        "Pasteboard generator type",
        "net.antelle.keeweb",
    ]

    // MARK: - State

    private let db: DatabaseManager
    private var cachedItems: [ClipboardItem] = []
    private var _version: Int = 0
    private var _capacity: Int
    private var lastChangeCount: Int = 0
    private var skipUntilChangeCount: Int = 0
    private nonisolated(unsafe) var timer: DispatchSourceTimer?
    private nonisolated(unsafe) var ocrTasks: [Int: Task<Void, Never>] = [:]

    private static let logger = Logger(
        subsystem: Bundle.main.bundleIdentifier ?? "io.github.airead.lingxi",
        category: "ClipboardStore"
    )

    static let imageDirectory: URL = {
        let appSupport = FileManager.default.urls(
            for: .applicationSupportDirectory, in: .userDomainMask
        ).first!
        let dir = appSupport
            .appendingPathComponent("LingXi")
            .appendingPathComponent("clipboard_images")
        try? FileManager.default.createDirectory(
            at: dir, withIntermediateDirectories: true
        )
        return dir
    }()

    // MARK: - Init

    // Assigned once in nonisolated init, then only awaited/cancelled in actor-isolated methods and deinit.
    private nonisolated(unsafe) var setupTask: Task<Void, Never>?

    init(database: DatabaseManager, capacity: Int = 200) {
        self.db = database
        self._capacity = capacity
        self.setupTask = Task { [self] in
            await createTable()
            await loadFromDatabase()
        }
    }

    // MARK: - Public API

    var items: [ClipboardItem] {
        cachedItems
    }

    var version: Int {
        _version
    }

    func itemsWithVersion() -> (items: [ClipboardItem], version: Int) {
        (cachedItems, _version)
    }

    func startMonitoring() {
        guard timer == nil else { return }

        lastChangeCount = NSPasteboard.general.changeCount

        let source = DispatchSource.makeTimerSource(queue: .main)
        source.schedule(
            deadline: .now() + pollInterval,
            repeating: pollInterval
        )
        source.setEventHandler { [weak self] in
            guard let self else { return }
            Task { await self.checkPasteboard() }
        }
        timer = source
        source.resume()
    }

    func stopMonitoring() {
        timer?.cancel()
        timer = nil
    }

    func delete(itemId: Int) async {
        await setupTask?.value
        ocrTasks[itemId]?.cancel()
        ocrTasks[itemId] = nil
        guard let index = cachedItems.firstIndex(where: { $0.id == itemId }) else { return }
        let item = cachedItems.remove(at: index)
        _version += 1

        if !item.imagePath.isEmpty {
            let fullPath = Self.imageDirectory
                .appendingPathComponent(item.imagePath).path
            try? FileManager.default.removeItem(atPath: fullPath)
        }

        await db.execute(
            "DELETE FROM clipboard_history WHERE id = ?",
            bindings: [String(itemId)]
        )
    }

    @discardableResult
    func writeToClipboard(itemId: Int) -> Bool {
        guard let item = cachedItems.first(where: { $0.id == itemId }) else {
            return false
        }

        switch item.contentType {
        case .text:
            let pb = Self.prepareTransientPasteboard(types: [.string])
            pb.setString(item.textContent, forType: .string)
            skipUntilChangeCount = pb.changeCount
            return true
        case .image:
            let fileURL = Self.imageDirectory.appendingPathComponent(item.imagePath)
            guard let pngData = try? Data(contentsOf: fileURL) else { return false }
            let pb = Self.prepareTransientPasteboard(types: [.png])
            pb.setData(pngData, forType: .png)
            skipUntilChangeCount = pb.changeCount
            return true
        }
    }

    func setCapacity(_ newCapacity: Int) async {
        guard newCapacity != _capacity else { return }
        await setupTask?.value
        _capacity = newCapacity
        await enforceCapacity()
    }

    // MARK: - Internal (for testing)

    func addTextEntry(_ text: String, sourceApp: String = "", sourceBundleId: String = "") async {
        await setupTask?.value
        let trimmed = text.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !trimmed.isEmpty else { return }
        guard trimmed.count <= maxTextLength else {
            Self.logger.debug("Skipping oversized text: \(trimmed.count) chars")
            return
        }

        // Dedup check — actor isolation guarantees exclusive access.
        if let newest = cachedItems.first, newest.contentType == .text,
           newest.textContent == trimmed
        {
            return
        }

        // DB transaction runs on DatabaseManager actor.
        let timestamp = Date().timeIntervalSince1970
        var newId = 0

        let ok = await db.transaction { tx in
            let inserted = tx.execute(
                """
                INSERT INTO clipboard_history
                    (content_type, text_content, timestamp, source_app, source_bundle_id)
                VALUES (?, ?, ?, ?, ?)
                """,
                bindings: [
                    ClipboardItem.ContentType.text.rawValue, trimmed, String(timestamp), sourceApp, sourceBundleId,
                ]
            )
            if inserted {
                newId = tx.lastInsertRowId
            }
            return inserted
        }

        guard ok, newId > 0 else { return }

        let item = ClipboardItem(
            id: newId,
            contentType: .text,
            textContent: trimmed,
            sourceApp: sourceApp,
            sourceBundleId: sourceBundleId,
            imagePath: "",
            imageWidth: 0,
            imageHeight: 0,
            imageSize: 0,
            ocrText: "",
            timestamp: timestamp
        )

        cachedItems.insert(item, at: 0)
        _version += 1
        let needsEviction = cachedItems.count > _capacity

        if needsEviction {
            await enforceCapacity()
        }
    }

    func addImageEntry(pngData: Data, sourceApp: String = "", sourceBundleId: String = "") async {
        await setupTask?.value

        guard let source = CGImageSourceCreateWithData(pngData as CFData, nil),
              let props = CGImageSourceCopyPropertiesAtIndex(source, 0, nil) as? [CFString: Any],
              let width = props[kCGImagePropertyPixelWidth] as? Int,
              let height = props[kCGImagePropertyPixelHeight] as? Int
        else { return }
        guard width >= 4, height >= 4 else {
            Self.logger.debug("Skipping tiny image: \(width)×\(height)")
            return
        }

        let hashPrefix = Self.sha256HashPrefix(pngData)

        if let newest = cachedItems.first, newest.contentType == .image,
           Self.extractHashPrefix(from: newest.imagePath) == hashPrefix
        {
            return
        }

        let timestamp = Date().timeIntervalSince1970
        let filename = "\(Int(timestamp))_\(hashPrefix).png"
        let fileURL = Self.imageDirectory.appendingPathComponent(filename)

        do {
            try pngData.write(to: fileURL)
        } catch {
            Self.logger.error("Failed to save image: \(error)")
            return
        }

        let fileSize = pngData.count
        var newId = 0

        let ok = await db.transaction { tx in
            let inserted = tx.execute(
                """
                INSERT INTO clipboard_history
                    (content_type, text_content, timestamp, source_app, source_bundle_id,
                     image_path, image_width, image_height, image_size)
                VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
                """,
                bindings: [
                    ClipboardItem.ContentType.image.rawValue, "", String(timestamp),
                    sourceApp, sourceBundleId,
                    filename, String(width), String(height), String(fileSize),
                ]
            )
            if inserted { newId = tx.lastInsertRowId }
            return inserted
        }

        guard ok, newId > 0 else {
            try? FileManager.default.removeItem(at: fileURL)
            return
        }

        let item = ClipboardItem(
            id: newId,
            contentType: .image,
            textContent: "",
            sourceApp: sourceApp,
            sourceBundleId: sourceBundleId,
            imagePath: filename,
            imageWidth: width,
            imageHeight: height,
            imageSize: fileSize,
            ocrText: "",
            timestamp: timestamp
        )

        cachedItems.insert(item, at: 0)
        _version += 1

        if cachedItems.count > _capacity {
            await enforceCapacity()
        }

        if width >= minOCRDimension, height >= minOCRDimension {
            ocrTasks[newId] = Task {
                await performOCR(itemId: newId, imageURL: fileURL)
                ocrTasks[newId] = nil
            }
        }
    }

    // MARK: - Private

    private func createTable() async {
        await db.execute("""
            CREATE TABLE IF NOT EXISTS clipboard_history (
                id               INTEGER PRIMARY KEY AUTOINCREMENT,
                content_type     TEXT    NOT NULL,
                text_content     TEXT    NOT NULL DEFAULT '',
                timestamp        REAL    NOT NULL,
                source_app       TEXT    NOT NULL DEFAULT '',
                source_bundle_id TEXT    NOT NULL DEFAULT '',
                image_path       TEXT    NOT NULL DEFAULT '',
                image_width      INTEGER NOT NULL DEFAULT 0,
                image_height     INTEGER NOT NULL DEFAULT 0,
                image_size       INTEGER NOT NULL DEFAULT 0,
                ocr_text         TEXT    NOT NULL DEFAULT ''
            )
            """)
        await db.execute(
            "CREATE INDEX IF NOT EXISTS idx_clipboard_timestamp ON clipboard_history(timestamp DESC)"
        )
    }

    private func loadFromDatabase() async {
        let rows = await db.query(
            """
            SELECT id, content_type, text_content, timestamp,
                   source_app, source_bundle_id,
                   image_path, image_width, image_height, image_size, ocr_text
            FROM clipboard_history
            ORDER BY timestamp DESC
            LIMIT ?
            """,
            bindings: [String(_capacity)]
        ) { row in
            ClipboardItem(
                id: row.int(at: 0),
                contentType: ClipboardItem.ContentType(rawValue: row.string(at: 1)) ?? .text,
                textContent: row.string(at: 2),
                sourceApp: row.string(at: 4),
                sourceBundleId: row.string(at: 5),
                imagePath: row.string(at: 6),
                imageWidth: row.int(at: 7),
                imageHeight: row.int(at: 8),
                imageSize: row.int(at: 9),
                ocrText: row.string(at: 10),
                timestamp: row.double(at: 3)
            )
        }

        cachedItems = rows
    }

    private func checkPasteboard() {
        let pb = NSPasteboard.general
        let count = pb.changeCount

        guard count != lastChangeCount else { return }
        lastChangeCount = count
        guard count > skipUntilChangeCount else { return }
        guard !Self.isConcealed(pb) else { return }

        let app = NSWorkspace.shared.frontmostApplication
        let frontApp = app?.localizedName ?? ""
        let frontBundleId = app?.bundleIdentifier ?? ""

        // Rich text copy (browser, Pages, etc.) includes a rendered image — prefer text
        let isRichText = Self.isRichText(pb)
        let pngData = Self.extractPNGData(from: pb)

        if !isRichText, let pngData {
            Task {
                await addImageEntry(
                    pngData: pngData, sourceApp: frontApp,
                    sourceBundleId: frontBundleId
                )
            }
        } else if let text = pb.string(forType: .string) {
            Task {
                await addTextEntry(
                    text, sourceApp: frontApp,
                    sourceBundleId: frontBundleId
                )
            }
        } else if let pngData {
            Task {
                await addImageEntry(
                    pngData: pngData, sourceApp: frontApp,
                    sourceBundleId: frontBundleId
                )
            }
        }
    }

    private static let richTextTypes: Set<String> = [
        NSPasteboard.PasteboardType.rtf.rawValue,
        NSPasteboard.PasteboardType.rtfd.rawValue,
        "public.html",
    ]

    private nonisolated static func isRichText(_ pasteboard: NSPasteboard) -> Bool {
        guard let types = pasteboard.types else { return false }
        return types.contains { richTextTypes.contains($0.rawValue) }
    }

    private nonisolated static func isConcealed(_ pasteboard: NSPasteboard) -> Bool {
        guard let types = pasteboard.types else { return false }
        return types.contains { concealedTypes.contains($0.rawValue) }
    }

    private func enforceCapacity() async {
        let capacity = _capacity

        var deletedEntries: [(id: Int, imagePath: String)] = []

        let ok = await db.transaction { tx in
            deletedEntries = tx.query(
                """
                SELECT id, image_path FROM clipboard_history
                WHERE id NOT IN (
                    SELECT id FROM clipboard_history ORDER BY timestamp DESC LIMIT ?
                )
                """,
                bindings: [String(capacity)]
            ) { row in (id: row.int(at: 0), imagePath: row.string(at: 1)) }

            guard !deletedEntries.isEmpty else { return true }

            let ids = deletedEntries.map { String($0.id) }.joined(separator: ",")
            tx.execute("DELETE FROM clipboard_history WHERE id IN (\(ids))")
            return true
        }

        guard ok, !deletedEntries.isEmpty else { return }

        for entry in deletedEntries {
            ocrTasks[entry.id]?.cancel()
            ocrTasks[entry.id] = nil

            if !entry.imagePath.isEmpty {
                let fullPath = Self.imageDirectory
                    .appendingPathComponent(entry.imagePath).path
                try? FileManager.default.removeItem(atPath: fullPath)
            }
        }

        cachedItems = Array(cachedItems.prefix(capacity))
        _version += 1
    }

    func awaitPendingOCR(itemId: Int) async {
        await ocrTasks[itemId]?.value
    }

    private func performOCR(itemId: Int, imageURL: URL) async {
        let text = await Self.recognizeText(at: imageURL)
        guard !Task.isCancelled, !text.isEmpty else { return }

        guard let index = cachedItems.firstIndex(where: { $0.id == itemId }) else { return }
        cachedItems[index].ocrText = text
        _version += 1

        await db.execute(
            "UPDATE clipboard_history SET ocr_text = ? WHERE id = ?",
            bindings: [text, String(itemId)]
        )
    }

    @concurrent
    private static func recognizeText(at url: URL) async -> String {
        let handler = VNImageRequestHandler(url: url)
        let request = VNRecognizeTextRequest()
        request.recognitionLevel = .accurate
        request.recognitionLanguages = ["zh-Hans", "zh-Hant", "en-US"]
        do {
            try handler.perform([request])
        } catch {
            logger.debug("OCR failed: \(error)")
            return ""
        }
        guard let results = request.results else { return "" }
        return results.compactMap { $0.topCandidates(1).first?.string }.joined(separator: "\n")
    }

    private nonisolated static func prepareTransientPasteboard(
        types: [NSPasteboard.PasteboardType]
    ) -> NSPasteboard {
        let pb = NSPasteboard.general
        pb.clearContents()
        pb.declareTypes(types + [concealedType, transientType], owner: nil)
        pb.setString("", forType: concealedType)
        pb.setString("", forType: transientType)
        return pb
    }

    private nonisolated static func sha256HashPrefix(_ data: Data) -> String {
        let digest = SHA256.hash(data: data)
        return digest.prefix(6).map { String(format: "%02x", $0) }.joined()
    }

    private nonisolated static func extractHashPrefix(from filename: String) -> String? {
        guard let dotIndex = filename.lastIndex(of: ".") else { return nil }
        let stem = filename[..<dotIndex]
        return stem.split(separator: "_").last.map(String.init)
    }

    private nonisolated static func extractPNGData(from pb: NSPasteboard) -> Data? {
        // Fast path: already PNG
        if let pngData = pb.data(forType: .png) { return pngData }
        // Slow path: convert any supported image format (TIFF, JPEG, PDF, etc.) to PNG
        let imageTypes: [NSPasteboard.PasteboardType] = [.tiff, .pdf]
        for type in imageTypes {
            if let data = pb.data(forType: type) {
                return imageToPNG(data)
            }
        }
        return nil
    }

    private nonisolated static func imageToPNG(_ data: Data) -> Data? {
        guard let image = NSImage(data: data),
              let tiffData = image.tiffRepresentation,
              let rep = NSBitmapImageRep(data: tiffData)
        else { return nil }
        return rep.representation(using: .png, properties: [:])
    }
}
