import AppKit
import OSLog

nonisolated struct ClipboardItem: Sendable {
    let id: Int
    let contentType: ContentType
    let textContent: String
    let sourceApp: String
    let sourceBundleId: String
    let imagePath: String
    let imageWidth: Int
    let imageHeight: Int
    let imageSize: Int
    var ocrText: String
    let timestamp: TimeInterval

    enum ContentType: String, Sendable {
        case text
        case image
    }
}

actor ClipboardStore {

    deinit {
        setupTask?.cancel()
        timer?.cancel()
    }

    // MARK: - Constants

    private let maxTextLength = 10240
    private let pollInterval: TimeInterval = 0.5

    private static let concealedTypeRaw = "org.nspasteboard.ConcealedType"
    private static let transientTypeRaw = "org.nspasteboard.TransientType"
    private static let concealedType = NSPasteboard.PasteboardType(concealedTypeRaw)
    private static let transientType = NSPasteboard.PasteboardType(transientTypeRaw)

    private static let concealedTypes: Set<String> = [
        concealedTypeRaw,
        transientTypeRaw,
        "org.nspasteboard.AutoGeneratedType",
        "com.agilebits.onepassword",
        "de.petermaurer.TransientPasteboardType",
        "com.typeit4me.clipping",
        "Pasteboard generator type",
        "net.antelle.keeweb",
    ]

    // MARK: - State

    private let db: DatabaseManager
    private var cachedItems: [ClipboardItem] = []
    private var _version: Int = 0
    private var _capacity: Int
    private var lastChangeCount: Int = 0
    private var skipUntilChangeCount: Int = 0
    private nonisolated(unsafe) var timer: DispatchSourceTimer?

    private static let logger = Logger(
        subsystem: Bundle.main.bundleIdentifier ?? "io.github.airead.lingxi",
        category: "ClipboardStore"
    )

    static let imageDirectory: URL = {
        let appSupport = FileManager.default.urls(
            for: .applicationSupportDirectory, in: .userDomainMask
        ).first!
        let dir = appSupport
            .appendingPathComponent("LingXi")
            .appendingPathComponent("clipboard_images")
        try? FileManager.default.createDirectory(
            at: dir, withIntermediateDirectories: true
        )
        return dir
    }()

    // MARK: - Init

    // Assigned once in nonisolated init, then only awaited/cancelled in actor-isolated methods and deinit.
    private nonisolated(unsafe) var setupTask: Task<Void, Never>?

    init(database: DatabaseManager, capacity: Int = 200) {
        self.db = database
        self._capacity = capacity
        self.setupTask = Task { [self] in
            await createTable()
            await loadFromDatabase()
        }
    }

    // MARK: - Public API

    var items: [ClipboardItem] {
        cachedItems
    }

    var version: Int {
        _version
    }

    func startMonitoring() {
        guard timer == nil else { return }

        lastChangeCount = NSPasteboard.general.changeCount

        let source = DispatchSource.makeTimerSource(queue: .main)
        source.schedule(
            deadline: .now() + pollInterval,
            repeating: pollInterval
        )
        source.setEventHandler { [weak self] in
            guard let self else { return }
            Task { await self.checkPasteboard() }
        }
        timer = source
        source.resume()
    }

    func stopMonitoring() {
        timer?.cancel()
        timer = nil
    }

    func delete(itemId: Int) async {
        await setupTask?.value
        let countBefore = cachedItems.count
        cachedItems.removeAll { $0.id == itemId }
        let removed = cachedItems.count < countBefore
        if removed { _version += 1 }

        guard removed else { return }
        await db.execute(
            "DELETE FROM clipboard_history WHERE id = ?",
            bindings: [String(itemId)]
        )
    }

    @discardableResult
    func writeToClipboard(itemId: Int) -> Bool {
        guard let item = cachedItems.first(where: { $0.id == itemId }) else {
            return false
        }

        switch item.contentType {
        case .text:
            let pb = NSPasteboard.general
            pb.clearContents()
            pb.declareTypes([.string, Self.concealedType, Self.transientType], owner: nil)
            pb.setString(item.textContent, forType: .string)
            pb.setString("", forType: Self.concealedType)
            pb.setString("", forType: Self.transientType)

            skipUntilChangeCount = pb.changeCount
            return true
        case .image:
            return false
        }
    }

    func setCapacity(_ newCapacity: Int) async {
        await setupTask?.value
        _capacity = newCapacity
        await enforceCapacity()
    }

    // MARK: - Internal (for testing)

    func addTextEntry(_ text: String, sourceApp: String = "", sourceBundleId: String = "") async {
        await setupTask?.value
        let trimmed = text.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !trimmed.isEmpty else { return }
        guard trimmed.count <= maxTextLength else {
            Self.logger.debug("Skipping oversized text: \(trimmed.count) chars")
            return
        }

        // Dedup check — actor isolation guarantees exclusive access.
        if let newest = cachedItems.first, newest.contentType == .text,
           newest.textContent == trimmed
        {
            return
        }

        // DB transaction runs on DatabaseManager actor.
        let timestamp = Date().timeIntervalSince1970
        var newId = 0

        let ok = await db.transaction { tx in
            let inserted = tx.execute(
                """
                INSERT INTO clipboard_history
                    (content_type, text_content, timestamp, source_app, source_bundle_id)
                VALUES (?, ?, ?, ?, ?)
                """,
                bindings: [
                    ClipboardItem.ContentType.text.rawValue, trimmed, String(timestamp), sourceApp, sourceBundleId,
                ]
            )
            if inserted {
                newId = tx.lastInsertRowId
            }
            return inserted
        }

        guard ok, newId > 0 else { return }

        let item = ClipboardItem(
            id: newId,
            contentType: .text,
            textContent: trimmed,
            sourceApp: sourceApp,
            sourceBundleId: sourceBundleId,
            imagePath: "",
            imageWidth: 0,
            imageHeight: 0,
            imageSize: 0,
            ocrText: "",
            timestamp: timestamp
        )

        cachedItems.insert(item, at: 0)
        _version += 1
        let needsEviction = cachedItems.count > _capacity

        if needsEviction {
            await enforceCapacity()
        }
    }

    // MARK: - Private

    private func createTable() async {
        await db.execute("""
            CREATE TABLE IF NOT EXISTS clipboard_history (
                id               INTEGER PRIMARY KEY AUTOINCREMENT,
                content_type     TEXT    NOT NULL,
                text_content     TEXT    NOT NULL DEFAULT '',
                timestamp        REAL    NOT NULL,
                source_app       TEXT    NOT NULL DEFAULT '',
                source_bundle_id TEXT    NOT NULL DEFAULT '',
                image_path       TEXT    NOT NULL DEFAULT '',
                image_width      INTEGER NOT NULL DEFAULT 0,
                image_height     INTEGER NOT NULL DEFAULT 0,
                image_size       INTEGER NOT NULL DEFAULT 0,
                ocr_text         TEXT    NOT NULL DEFAULT ''
            )
            """)
        await db.execute(
            "CREATE INDEX IF NOT EXISTS idx_clipboard_timestamp ON clipboard_history(timestamp DESC)"
        )
    }

    private func loadFromDatabase() async {
        let rows = await db.query(
            """
            SELECT id, content_type, text_content, timestamp,
                   source_app, source_bundle_id,
                   image_path, image_width, image_height, image_size, ocr_text
            FROM clipboard_history
            ORDER BY timestamp DESC
            LIMIT ?
            """,
            bindings: [String(_capacity)]
        ) { row in
            ClipboardItem(
                id: row.int(at: 0),
                contentType: ClipboardItem.ContentType(rawValue: row.string(at: 1)) ?? .text,
                textContent: row.string(at: 2),
                sourceApp: row.string(at: 4),
                sourceBundleId: row.string(at: 5),
                imagePath: row.string(at: 6),
                imageWidth: row.int(at: 7),
                imageHeight: row.int(at: 8),
                imageSize: row.int(at: 9),
                ocrText: row.string(at: 10),
                timestamp: row.double(at: 3)
            )
        }

        cachedItems = rows
    }

    private func checkPasteboard() {
        let pb = NSPasteboard.general
        let count = pb.changeCount

        guard count != lastChangeCount else { return }
        lastChangeCount = count
        guard count > skipUntilChangeCount else { return }
        guard !Self.isConcealed(pb) else { return }

        if let text = pb.string(forType: .string) {
            let app = NSWorkspace.shared.frontmostApplication
            let frontApp = app?.localizedName ?? ""
            let frontBundleId = app?.bundleIdentifier ?? ""
            Task {
                await addTextEntry(text, sourceApp: frontApp, sourceBundleId: frontBundleId)
            }
        }
    }

    private nonisolated static func isConcealed(_ pasteboard: NSPasteboard) -> Bool {
        guard let types = pasteboard.types else { return false }
        return types.contains { concealedTypes.contains($0.rawValue) }
    }

    private func enforceCapacity() async {
        let capacity = _capacity

        var deletedEntries: [(id: Int, imagePath: String)] = []

        let ok = await db.transaction { tx in
            deletedEntries = tx.query(
                """
                SELECT id, image_path FROM clipboard_history
                WHERE id NOT IN (
                    SELECT id FROM clipboard_history ORDER BY timestamp DESC LIMIT ?
                )
                """,
                bindings: [String(capacity)]
            ) { row in (id: row.int(at: 0), imagePath: row.string(at: 1)) }

            guard !deletedEntries.isEmpty else { return true }

            let ids = deletedEntries.map { String($0.id) }.joined(separator: ",")
            tx.execute("DELETE FROM clipboard_history WHERE id IN (\(ids))")
            return true
        }

        guard ok, !deletedEntries.isEmpty else { return }

        for entry in deletedEntries where !entry.imagePath.isEmpty {
            let fullPath = Self.imageDirectory
                .appendingPathComponent(entry.imagePath).path
            try? FileManager.default.removeItem(atPath: fullPath)
        }

        cachedItems = Array(cachedItems.prefix(capacity))
        _version += 1
    }
}
